using TradeAgent.Core;
using TradeAgent.Gateway;

namespace TradeAgent.AgentRuntime;

/// <summary>
/// The two kinds of runtime a seat can run on, as far as what it can REACH is concerned: a vendor's command-line AI,
/// started in the seat's folder as the owner's own user (codex, OpenCode, a custom one — they reach the same things), or
/// the app-owned harness, which runs inside TradeAgent's process and acts only through the tools the app grants it.
/// </summary>
public enum RuntimeClass { Cli, Harness }

/// <summary>
/// One verb a seat may use. <see cref="Op"/> is the gateway's own operation; <see cref="Invocation"/> is how this runtime
/// asks for it — the schema's command form on a CLI (<c>trade data bars --pair P …</c>), the tool that carries it on the
/// harness (<c>data</c>).
/// </summary>
public sealed record ReachVerb(string Op, string Invocation, bool Mutating);

/// <summary>One kind of file a seat hands back: the publication kind, the path it is read from, and its cap in lines.</summary>
public sealed record ReachHandBack(string Kind, string Path, int Lines);

/// <summary>
/// WHAT ONE SEAT CAN ACTUALLY REACH ON ONE RUNTIME, read from the code that grants or refuses it and from nowhere else
/// (<c>U-canon</c>, VISION § 6.7: the canon's capability section is "generated by the app from what it grants that seat
/// and runtime … never written as prose a later build can falsify").
///
/// <para><b>Referenced, never copied.</b> The verbs are <see cref="GatewaySchema.Ops"/> — what the gateway serves to
/// <c>trade schema</c> — or the ops each harness tool carries (<see cref="GrantedWorkerTools.OpsOf"/>), less
/// <see cref="Ops.Mutating"/> for a role <see cref="CouncilRoles.MayPlaceOrders"/> refuses, which is the line the pipe
/// refuses them on. The harness's tools and its write roots are <see cref="GrantedWorkerTools"/>'s own; a CLI's walls
/// are <see cref="Containment.Sandbox"/>'s answer; the folders are <see cref="WorkspaceBuilder.SubDirs"/> and
/// <see cref="CouncilRoles"/>; the wake is <see cref="MissionLoop.WakeFile"/> and <see cref="MissionOptions.MaxDelay"/>;
/// what a seat hands back is <see cref="CouncilRelay"/>'s grammar. A list here would be a second grant nobody enforces,
/// which is exactly the drift this record exists to end: the canon used to promise the harness a shell, the internet,
/// <c>scripts/</c> and a wake file it could not write (R20 § 1).</para>
///
/// <para><b>It grants nothing.</b> Nothing reads this to decide what a seat may do — the gateway, the tools, the relay and
/// the loop each decide that themselves, as before. This is the description of their decisions the canon is rendered
/// from, and the binding test holds the canon to it.</para>
/// </summary>
public sealed record AgentReach
{
    /// <summary>The owner's drop folder, as a seat's own folder sees it: one level up and beside it.</summary>
    public const string Inbox = "../" + MaterialScanner.InboxDir;

    /// <summary>The seat's own folder, as a read root: every relative path inside it.</summary>
    public const string OwnFolder = "";

    public required string Role { get; init; }
    public required RuntimeClass Runtime { get; init; }

    /// <summary>
    /// The operating system the seat's own program runs on, or null on the harness, which runs no program of its own and
    /// reaches the computer only through its tools. Never a claim about the machine beyond that: the canon used to say
    /// "personal Windows laptop" and "modest laptop" to a seat running on a Mac, and the switch-on host is a Linux server.
    /// </summary>
    public required string? Os { get; init; }

    /// <summary>
    /// Whether the seat runs code of its own — writes and runs programs, installs packages, uses a shell and the internet.
    /// True on a CLI (the vendor's program runs in its folder with those powers); false on the harness, whose only way to
    /// act is a tool call the app executes.
    /// </summary>
    public required bool RunsCode { get; init; }

    /// <summary>Where it reads: <see cref="OwnFolder"/> for its whole folder, <see cref="Inbox"/> for the owner's drop folder.</summary>
    public required IReadOnlyList<string> Reads { get; init; }

    /// <summary>The top-level folders inside its own folder it writes into. Nothing outside its folder.</summary>
    public required IReadOnlyList<string> Writes { get; init; }

    /// <summary>
    /// Whether anything ENFORCES <see cref="Reads"/> and <see cref="Writes"/>. False is a convention the canon asks for and
    /// nothing checks — the CLI today, with no operating-system sandbox; true is a wall the app's code holds.
    /// </summary>
    public required bool Walled { get; init; }

    /// <summary>The file inside its folder it writes to ask for its next wake, or null when it has none it can write.</summary>
    public required string? WakeFile { get; init; }

    /// <summary>The longest wake it can ask for, or null with no wake file.</summary>
    public required TimeSpan? WakeCap { get; init; }

    /// <summary>What it hands back, each kind with the path the relay reads it from and its cap.</summary>
    public required IReadOnlyList<ReachHandBack> HandsBack { get; init; }

    /// <summary>The verbs it may use. The ones the gateway refuses it are not here.</summary>
    public required IReadOnlyList<ReachVerb> Verbs { get; init; }

    /// <summary>Its tools: the one command on its PATH on a CLI, the granted tools on the harness.</summary>
    public required IReadOnlyList<string> Tools { get; init; }

    /// <summary>How many turns one session carries before a fresh one starts. One is every turn.</summary>
    public required int TurnsPerSession { get; init; }

    /// <summary>Whether the gateway lets this seat place, change or cancel an order.</summary>
    public bool MayPlaceOrders => CouncilRoles.MayPlaceOrders(Role);

    /// <summary>Whether it reads the owner's drop folder at all.</summary>
    public bool ReadsInbox => Reads.Contains(Inbox);

    /// <summary>Whether it can ask for its own next wake.</summary>
    public bool Wakes => WakeFile is not null;

    /// <summary>The verb for this op, or null when the seat may not use it on this runtime.</summary>
    public ReachVerb? Verb(string op) => Verbs.FirstOrDefault(v => v.Op == op);

    /// <summary>Whether a path relative to the seat's folder is somewhere it writes.</summary>
    public bool WritesInto(string path) =>
        Writes.Contains(TopFolder(path.StartsWith("./", StringComparison.Ordinal) ? path[2..] : path), StringComparer.Ordinal);

    /// <summary>
    /// The reach of one role on one runtime class, as this build grants it. <paramref name="turnsPerSession"/> is the
    /// owner's setting for a CLI session's length (<c>TradeAgentSettings.MissionTurnsPerSession</c>), or null for the
    /// loop's own default; the harness ignores it, because it starts every turn fresh.
    /// </summary>
    public static AgentReach For(string role, RuntimeClass runtime, int? turnsPerSession = null)
    {
        bool Allowed(string op) => CouncilRoles.MayPlaceOrders(role) || !Ops.IsMutating(op);

        var handsBack = CouncilRelay.KindsFor(role)
            .Select(k => new ReachHandBack(k, $"{CouncilRoles.OutDir}/{CouncilRelay.Pattern(k).Replace("*", "<attempt>")}",
                CouncilRelay.Limit(k)))
            .ToList();

        if (runtime == RuntimeClass.Cli)
        {
            // THE CLI'S VERBS ARE THE GATEWAY'S, less what the gateway refuses this role. Its one tool is the command
            // those forms are spelled with — the first word of every one of them.
            var verbs = GatewaySchema.Ops().Where(o => Allowed(o.Op))
                .Select(o => new ReachVerb(o.Op, o.Cli, Ops.IsMutating(o.Op))).ToList();
            var writes = WorkspaceBuilder.SubDirs.Append(CouncilRoles.OutDir).Append(TopFolder(MissionLoop.WakeFile)).ToList();
            var options = new MissionOptions();

            return new AgentReach
            {
                Role = role,
                Runtime = runtime,
                Os = OsName(),
                RunsCode = true,
                Reads = [OwnFolder, Inbox],
                Writes = writes,
                Walled = Containment.Sandbox().Ok,
                WakeFile = MissionLoop.WakeFile,
                WakeCap = options.MaxDelay,
                HandsBack = handsBack,
                Verbs = verbs,
                Tools = [.. verbs.Select(v => v.Invocation.Split(' ')[0]).Distinct(StringComparer.Ordinal)],
                TurnsPerSession = Math.Max(1, turnsPerSession ?? options.TurnsPerSession)
            };
        }

        // THE HARNESS: its tools, the ops each one carries, and the two folders `write_file` accepts — all of them
        // GrantedWorkerTools' own. It reads its whole folder (`read_file` takes any path inside it, `in/` included) and
        // nothing outside it, and the wake file is not in a folder it can write, so it has no wake to ask for.
        var tools = GrantedWorkerTools.Granted.Select(t => t.Name).ToList();
        var harnessVerbs = tools
            .SelectMany(t => GrantedWorkerTools.OpsOf(t).Where(Allowed).Select(op => new ReachVerb(op, t, Ops.IsMutating(op))))
            .ToList();
        var harnessWrites = GrantedWorkerTools.Writable.ToList();
        var wakes = harnessWrites.Contains(TopFolder(MissionLoop.WakeFile), StringComparer.Ordinal);

        return new AgentReach
        {
            Role = role,
            Runtime = runtime,
            Os = null,
            RunsCode = false,
            Reads = [OwnFolder],
            Writes = harnessWrites,
            Walled = true,
            WakeFile = wakes ? MissionLoop.WakeFile : null,
            WakeCap = wakes ? new MissionOptions().MaxDelay : null,
            HandsBack = handsBack.Where(h => harnessWrites.Contains(TopFolder(h.Path), StringComparer.Ordinal)).ToList(),
            Verbs = harnessVerbs,
            Tools = tools,
            TurnsPerSession = 1
        };
    }

    /// <summary>The first folder of a path relative to a seat's own folder.</summary>
    public static string TopFolder(string path) => path.Replace('\\', '/').Split('/')[0];

    /// <summary>The operating system's name in the words an owner uses, never a claim about the machine beyond it.</summary>
    public static string OsName() =>
        OperatingSystem.IsWindows() ? "Windows"
        : OperatingSystem.IsMacOS() ? "macOS"
        : OperatingSystem.IsLinux() ? "Linux"
        : System.Runtime.InteropServices.RuntimeInformation.OSDescription;
}
